name: Proxy Get

on: 
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches: 
      - master
  schedule:
    - cron: '0 1/6 * * *'
  watch:
    types: [started]
   
jobs:
   Task:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests/lxml  #安装requests lxml
      run: |
        pip install requests
        pip install lxml
    - name: run
      run: | 
        python proxy.py 
        echo proxy get at `date -d'+8 hours' +%Y-%m-%d/%H:%M:%S` >>proxy.log
    - name: Commit #
      run: |
        git config --global user.email oldboy_prq@163.com
        git config --global user.name rosepig
        git add .
        git commit -m "add time" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
